#!/bin/sh
set -e

#Set paths
GEN="../build/util/makecbind"
PASBINDDIR="../src/bind"
OUT="./linst-cbind"

if [ -e $GEN ]; then
 $GEN -i $PASBINDDIR/liappmgr.pas -o $OUT/li-manager.h --template=$OUT/cheader.template
 $GEN -i $PASBINDDIR/liinstaller.pas -o $OUT/li-installer.h --template=$OUT/cheader.template
 $GEN -i $PASBINDDIR/liappupdate.pas -o $OUT/li-updater.h --template=$OUT/cheader.template
 $GEN -i ../src/litypes.pas -o $OUT/li-types.h --template=$OUT/cheader.template
else
 echo "MakeCBind was not found!"
 exit 1
fi
