#!/bin/sh
set -e

#Set paths
GEN="../build/util/bindingtool"
PASBINDDIR="../src/bind"
OUT="./linst-cbind"

if [ -e $GEN ]; then
 $GEN --pastoc -i $PASBINDDIR/liappmgr.pas -o $OUT/li-manager.h --template=$OUT/cheader.template
 $GEN --pastoc -i $PASBINDDIR/liinstaller.pas -o $OUT/li-installer.h --template=$OUT/cheader.template
 $GEN --pastoc -i $PASBINDDIR/liappupdate.pas -o $OUT/li-updater.h --template=$OUT/cheader.template
 $GEN --pastoc -i ../src/litypes.pas -o $OUT/li-types.h --template=$OUT/cheader.template
else
 echo "BindingTool was not found!"
 exit 1
fi
