#! /bin/sh
#DEBHELPER#
set -e

echo "Uninstalling mime extensions..."
xdg-mime uninstall '/usr/share/listaller/mime/x-ipk.xml'
xdg-mime uninstall '/usr/share/listaller/mime/x-ips.xml'
xdg-icon-resource uninstall --context mimetypes --size 64 'mime-ipk' 'application-x-ipk'
xdg-icon-resource uninstall --context mimetypes --size 64 'mime-ips' 'text-ips-script'
update-mime-database '/usr/share/mime'
echo "Done."
