.TH libuild 1 "July 19, 2010" "" "libuild - Listaller package builder"

.SH NAME
libuild \- program for...

.SH SYNOPSIS
.B libuild
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B libuild
program. This program...
.PP
\fBlibuild\fP is for...

.SH OPTIONS
.B
.IP -OPTION
This option...

.SH EXAMPLE

.SH "SEE ALSO"

