.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH LIBUILD 1 "JUNE 2011" LISTALLER "User Manuals"
.SH NAME
libuild - Build Listaller IPK packages

.SH SYNOPSIS
.B libuild
.I OPTIONS
.B

.SH DESCRIPTION

LiBuild is a simple tool to build IPK application packages directly
from software sources or binary files using a package recipe.

.SH OPTIONS

.IP "-b --build"
Build IPK package in the current working directory.

.IP "-s --sourcedir" "DIRECTORY"
Set the IPK package source directory.

.IP "-o --outdir" "DIRECTORY"
Set an output path were the resulting package should be stored.

.IP --sign
Sign the resulting package with your GNUPG key.

.IP --version
Display version number of libuild

.SH AUTHOR
Matthias Klumpp

.SH "COPYRIGHT"
\(co 2009-2011 Matthias Klumpp <matthias@tenstral.net>
