.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PATCHELF 1 "JUNE 2011" LISTALLER "User Manuals"
.SH NAME
libuild - Build Listaller IPK packages

.SH SYNOPSIS
.B libuild
.I OPTION
.B
.I FILE
.B

.SH DESCRIPTION

LiBuild is a simple tool to build IPK application packages directly
from software sources or binary files using a package recipe.

.SH OPTIONS

The single option given operates on a given FILE, editing in place.

.IP "--sign"
Sign the resulting package

.IP --version
Shows the version of libuild.

.SH AUTHOR
Matthias Klumpp <matthias@nlinux.org>

