#!/bin/sh

echo "Validating document XML..."
cd pages
PAGES=$(find . -name '*.page')
yelp-check validate $PAGES
yelp-check links $PAGES
yelp-check status $PAGES
cd ..
#xmllint --noout --xinclude --relaxng $(dirname $0)/1.0/mallard-1.0.rng `find . -name '*.page'`

echo "Finished."
