#!/usr/bin/env bash
# Parses command line options. Currently supported options are:
#
# DESTDIR		Destination root directory
set -e

for arg; do
  case $arg in
    DESTDIR=*) DESTDIR=${arg#DESTDIR=};;
    prefix=*) prefix=${arg#prefix=};;
    libdir=*) libdir=${arg#libdir=};;
  esac;
done

if [ -z "$prefix" ]; then
   export prefix="/usr"
fi
if [ -z "$libdir" ]; then
   export libdir="$prefix/lib"
fi

echo "Installing development files..."
mkdir -p $DESTDIR$prefix/include/Listaller
mkdir -p $DESTDIR$prefix/share/pascal/listaller
mkdir -p $DESTDIR$libdir/pkgconfig/

#Copy C headers
cp ../lib/linst-cbind/*.h $DESTDIR$prefix/include/Listaller/
cp ../lib/linst-cbind/*.pc $DESTDIR$libdir/pkgconfig/
#Link library
CUR=$(pwd)
cd $DESTDIR$libdir
if [ ! -f liblistaller.so ]; then
ln -s $libdir/liblistaller.so.0.4 liblistaller.so
fi
cd $CUR
#Copy Pascal units
cp ./bind/liappmgr.pas $DESTDIR$prefix/share/pascal/listaller
cp ./bind/liappupdate.pas $DESTDIR$prefix/share/pascal/listaller
cp ./bind/liinstaller.pas $DESTDIR$prefix/share/pascal/listaller
cp ./litypes.pas $DESTDIR$prefix/share/pascal/listaller

echo "Finished installation of development files."
