#!/usr/bin/env bash
#
# DESTDIR		Destination root directory

set -e

for arg; do
  case $arg in
    DESTDIR=*) DESTDIR=${arg#DESTDIR=};;
  esac;
done

# Detects and parses the architecture
ARCH=$(uname -m)

case "$ARCH" in
 "i686") ARCH="i386";;
 "i586") ARCH="i386";;
 "i486") ARCH="i386";;
esac

echo "Target architecture: $ARCH"

if [ "$ARCH" == "x86_64" ]; then
LCLDir="/usr/lib64/lazarus"
else
LCLDir="/usr/lib/lazarus"
fi

echo "LAZTarget: $LCLDir"

OS="linux"

#Initialize build dirs
# Create necessary dirs
mkdir -p ../build
mkdir -p ../build/locale
mkdir -p ../build/lib_$ARCH-$OS
mkdir -p ../build/$ARCH-$OS

echo "Target operating system: $OS"
echo "Active widgetset: $WIDGET"

echo "Starting new Listaller build..."

echo "Compiling libinstaller library..."
lazbuild -B --ws=nogui ../lib/libinstaller.lpr
if [ ! -f "../build/libinstaller.so" ]; then
 cd ../build
 ln -s libinstaller.so.0.4.0 libinstaller.so.0.4
 ln -s libinstaller.so.0.4 libinstaller.so
 cd ../src
fi

echo "Compiling Listaller daemon..."
lazbuild -B --ws=nogui ./daemon/listallerd.lpr

echo "Compiling command-line tool..."
lazbuild -B --ws=nogui ./cmdtools/lipa.lpr
#fpc -MObjFPC -Sgi -CX -O1 -gl -XX -vewhi -l -Fuabbrevia/ -Fusynapse/ -Fu$LCLDir/lcl/units/$ARCH-$OS/ -Fu$LCLDir/lcl/units/$ARCH-$OS/nogui/ -Fu. -FUbin/ -vm5024 -FEbin/ -olipa -dOpbCompat lipa.lpr
echo "Compiling package build tool..."
lazbuild -B --ws=nogui ./cmdtools/libuild.lpr
#fpc -MObjFPC -Sgi -CX -O1 -gl -XX -vewnhi -l -Fuopbitmap/ -Fuabbrevia/ -Fu$LCLDir/lcl/units/$ARCH-$OS/ -Fu$LCLDir/lcl/units/$ARCH-$OS/nogui/ -Fu. -FUbin/ -FEbin/ -olibuild -dOpbCompat libuild.lpr

#Compiling lanuage files
echo "Generating language files..."
for i in `find ../data/locale -name "*.po"`
do
echo "Format $i"
msgfmt -o `expr substr $i 1 $(( ${#i} - 3 ))`.mo $i
mv `expr substr $i 1 $(( ${#i} - 3 ))`.mo ../build/locale/
done

echo "Listaller build completed."
